### PR TITLE
SmbShare: Bugfix to enable change of the path when the share already exists.

### LINKED ISSUE #215: SmbShare: If the Share exists but with the wrong Path, the resource does not update the path
#### Details of the scenario you tried and the problem that is occurring
*This originated from https://github.com/PowerShell/xSmbShare/issues/10 and was moved here when the module xSmbShare was deprecated.*

If the Share exists and the Path is not consistent with the desired state, the resource does not update the path.

#### Verbose logs showing the problem
Not available.

#### Suggested solution to the issue
The path cannot be updated without recreating the share, since Set-SmbShare do not support the parameter Path, and New-SmbShare does. Recreating the share could potentially remove configuration that has not been enforced by the DSC configuration. We should support recreating the share, but only if the user expressively allow that by using, for example, a resource parameter Force.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Any configuration where the desired path mismatch the actual path.

#### The operating system the target node is running
n/a

#### Version and build of PowerShell the target node is running
n/a

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

### PR DESCRIPTION
**Pull request by danielboth**
#### Pull Request (PR) description
This changes enables the SmbShare resource to change the path on an existing share. To ensure a user does this consciously, a parameter Force is added to the resource. Force needs to be true for the resource to drop and recreate the share on the new path. 

If the user did not set Force to true, a warning will be displayed stating the resource cannot get into desired state without setting Force to true.

#### This Pull Request (PR) fixes the following issues
- Fixes #215

#### Task list

- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md in the resource folder.
- [X] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/286)

### CODE REVIEW

**Comment by danielboth** [comment]
Hi @PlagueHO, on another branch I have a fix for #284 (https://github.com/danielboth/ComputerManagementDsc/tree/SmbShare-ScopeName-support). That one builds on the features I've added in this branch, would you like to review those in one go, or that we first merge this one?

**Comment by PlagueHO** [comment]
Hi @danielboth - can you resolve the conflicts on this one?

My feeling is to complete this PR first (as it is a bug fix) and then we'll get the feature one through.

**Comment by danielboth** [comment]
Good, I got the same feeling (the reason I splitted them to start with), so let's get this one through first. Just resolved the merge conflict.

**Comment by PlagueHO** [comment]
Closing/Reopening to kick CI again.

**Pull request merged**
