### PR TITLE
Add SystemLocale Resource - Fixes #50

### LINKED ISSUE #50: Move SystemLocale resource from SystemLocaleDSC to xComputerManagement
The SystemLocale resource currently resides inside of it's own module (SystemLocaleDSC).
I believe it makes more sense inside of xComputerManagement\xComputer resource as an optional parameter.

Let me know what you guys think. I've already submitted a PR ([#49](https://github.com/PowerShell/xComputerManagement/pull/49))

Liam

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR migrates SystemLocale from SystemLocaleDsc.

#### This Pull Request (PR) fixes the following issues

- Fixes #50

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing this one?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/288)

### CODE REVIEW

**Comment by johlju** [comment]
Starting review. I see if I have time to finish, if not I will finish tomorrow.

**Comment by johlju** [comment]
Oh it become far less to review now after a correct rebase 😄

**Comment by PlagueHO** [comment]
Something really odd is going on here @johlju, @SSvilen: The Hash table checks are telling me there is hash table style violations, but I can't see any: https://ci.appveyor.com/project/PowerShell/computermanagementdsc/builds/28707989?fullLog=true

All the tests pass locally. I've not noticed this before. Can either of you see anything wrong with the Hash tables that would cause this check to fail on AppVeyor but pass locally?

I'm also seeing this in NetworkingDsc: https://ci.appveyor.com/project/PlagueHO/networkingdsc?fullLog=true#L1286

Are you seeing this on any of yours @johlju?

**Comment by PlagueHO** [comment]
@SSvilen, the strange thing is that the hash table tests all pass locally (and in VS Code). @johlju has suggested this might be related to CRLF related, so I'm testing with a .gitattributes. Will get back shortly.

**Comment by SSvilen** [comment]
@PlagueHO  Using the preview extensions - nothing detected. Got back to official one - style violation was immediately show and removing back tick resolves it.  
Should I do a quick fix about it? 
I thought actually that back tick is considered as a bad practice nowadays.

**Comment by PlagueHO** [comment]
@SSvilen - the backtick issue would only explain a few of the violations (not many). Not sure what is causing the other ones. I don't think the back tick is a bad practice, unless it is not required. In this case if we didn't use it, the line would be very long. Admittedly, it would probably be better to create a parameter splat though. @johlju - what do you think? Allow the backtick?

**Comment by PlagueHO** [comment]
@SSvilen - It doesn't look like the .GitAttributes is going to fix the issue either. I suspect there is an issue with the regex and CR vs CRLF that will need to be addressed.

**Comment by johlju** [comment]
@SSvilen would be awesome if you could help resolve that line ending problem, seeing that in other modules as well. Thank you @SSvilen 🙇

**Comment by PlagueHO** [comment]
@johlju - should be good to go now!

**Comment by PlagueHO** [comment]
Hi @johlju - I've squash rebased this to clean up the commits and resolve conflicts. So hopefully good to go.

**Pull request merged**
