### PR TITLE
ScheduledTask: Add support for Group Managed Service Accounts

### LINKED ISSUE #111: xScheduledTask - missing option to configure tasks with gMSA accounts.
At the moment there is no option to specify gMSA account as ExecuteAsCredential. Attempt to do that (by passing credential w/o password) will result in error:

```
The password supplied to the Desired State Configuration resource MSFT_xScheduledTask is not valid. The password cannot be null or empty.
```

Following instructions here it should be possible with the command used inside this resource:
https://blogs.technet.microsoft.com/askpfeplat/2012/12/16/windows-server-2012-group-managed-service-accounts/

The main difference I see is that this instructions suggest to use `New-ScheduledTaskPrincipal` and pass object created by it to `-Principal` parameter on `Register-ScheduleTask` command.

As this looks like a different code path from existing one I think it would be best to support it in separate parameter (mutually exclusive with ExecuteAsCredential), but would like to first verify this is not already planned to be addressed in a different manner.

As a result we can't use the resource to configure large portion of scheduled tasks that require gMSA account to run correctly.

### PR DESCRIPTION
**Pull request by danielboth**
**Pull Request (PR) description**
This PR enables the use of Group Managed Service Accounts in the ScheduledTask resource. It enables the user to setup a scheduled task using a AD ServiceAccount and will set the task to 'Run whether user is logged on or not'. 

**This Pull Request (PR) fixes the following issues:**
Fixes #111 

**Task list:**
- [X] Change details added to Unreleased section of CHANGELOG.md?
- [X] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [X] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/174)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO do you have time to review this one? This one seems it falls under the same functionality as the PR and the comment https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/441#issuecomment-417053633

**Comment by PlagueHO** [comment]
How did I miss this! @danielboth - are you able to fix the merge conflicts? Sorry about the delay. I'll get onto reviewing this.

**Comment by danielboth** [comment]
Hi @PlagueHO, I pulled the latest dev to get my branch up to date a few days ago, no merge conflicts fortunately :). Can you continue the review?

**Comment by ImMattAsh** [comment]
@PlagueHO - sorry if you're not the person to ask, but I was just curious if there is a planned release to PSGallery where this feature will be available. Looks like last version of 4.1.0.0 was prior to this pull request being closed. If this information can be found elsewhere, I apologize. Please feel free to point me in the direction. Thanks!

**Comment by PlagueHO** [comment]
Hi @ImMattAsh - the latest version in the PSGallery is 6.0.0.0 I think (there was also a 5.0.0.0, 5.1.0.0, 5.2.0.0): https://www.powershellgallery.com/packages/ComputerManagementDsc/6.0.0.0. Might have been a PS Gallery glitch? The best way to see what has been released month to month in the DSC Resource kit is by looking here: https://blogs.msdn.microsoft.com/powershell/tag/dsc-resource-kit/

**Comment by PlagueHO** [comment]
Ah right! Of course. Glad all working and no worries at all.

**Pull request merged**
