### PR TITLE
Opt-in to validate localization, and Removed 'SupportsShouldProcess' - Fixes #217

### LINKED ISSUE #217: Opt-In to Common Tests - Validating Localization
There are new 'Common Tests - Validating Localization' in DSCResource.Helpers.

Opt-in to these tests and resolve any issues.

### LINKED ISSUE #218: Combine ComputerManagementDsc.ResourceHelpers into ComputerManagementDsc.Common
There is no point in having two modules providing "common" functions for use in the resources as both are usually loaded. So combine them into a single module.

### LINKED ISSUE #219: PowerShellExecutionPolicy: Should not be using SupportsShouldProcess
Resource should not be using `SupportsShouldProcess` as DSC resource cannot support that since it is not run interactively.

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- Opt-in to common test to validate localization. Fixed localization strings
  in resources - Fixes [Issue #217](https://github.com/PowerShell/ComputerManagementDsc/issues/217).
- PowerShellExecutionPolicy:
  - Removed `SupportsShouldProcess` as it cannot be used with DSC - Fixes
    [Issue #219](https://github.com/PowerShell/ComputerManagementDsc/issues/219).
- Combined all ComputerManagementDsc.ResourceHelper module functions into
  ComputerManagementDsc.Common module - Fixes [Issue #218](https://github.com/PowerShell/ComputerManagementDsc/issues/218).
  - Minor code cleanup against style guideline.
  - Remove code from `New-InvalidOperationException` because it was a
    code path that could never could be used due to that the parameter
    validation prevented the helper function being called that way.
  - Updated all `Get-LocalizationData` to latest version from
    [DSCResource.Template](https://github.com/PowerShell/DSCResource.Template).
  - Fixed an issue with the helper function `Test-IsNanoServer` that
    prevented it to work. Though the helper function is not used, so this
    issue was not caught until now when unit tests was added.
  - Improved code coverage.

#### This Pull Request (PR) fixes the following issues
- Fixes #217 
- Fixes #218 
- Fixes #219 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/216)

### CODE REVIEW

**Comment by johlju** [comment]
CLosing and reopening to kick off the updated localization common test.

**Comment by PlagueHO** [comment]
This should be able to come out of draft now that the PR to DSCResources.Test was merged.

**Comment by johlju** [comment]
@PlagueHO I'm fixing stuff for this PR to increase coverage

**Comment by johlju** [comment]
@PlagueHO Not sure where the last 4 misses come from.

**Comment by johlju** [comment]
It ready for review again! Let me knoe if I need to squash more coverage :p

**Pull request merged**
