### PR TITLE
SmbShare: Adding new resource

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
This moves the resource xSmbShare to the module ComputerManagementDsc, and deprecate the xSmbShare module.

#### This Pull Request (PR) fixes the following issues
n/a

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/211)

### CODE REVIEW

**Comment by johlju** [comment]
Working on integration tests next, and saw now that I missed some documentation in the resource folder, and the README.md. 

@PlagueHO testing a draft PR to see if it helps the review or discussions from the community.

**Comment by PlagueHO** [comment]
Oh right. Doh! I guess it should be have the needs review then!

**Comment by johlju** [comment]
@PlagueHO The examples fails to compile in my fork because it sees multiple versions on ComputerManagementDsc. Is it something in my change that is causing that? 

See test run in my forks working branch:
https://ci.appveyor.com/project/johlju/computermanagementdsc/builds/23490491?fullLog=true#L4983

**Comment by PlagueHO** [comment]
@johlju - I don't know if this is the cause of the issue, but you do need to rebase I think as you need to pick up the more recent changes.

I couldn't see anything in your code that looked like it would cause this problem! That is strange. Does it work locally?

**Comment by PlagueHO** [comment]
P.S. as soon as #195 is through I'm going to refactor this module to get rid of the harness - which will make it simpler and easier to debug issues like this.

**Comment by johlju** [comment]
Yep, I will rebase as soon as I get the last of the integration tests fixed. After that I take it out of draft and AppVeyor will run for the PR. We debug after that why there are two modules present on the node, if the problem is still there.

**Comment by johlju** [comment]
I have a slight problem with this resource, and it is the default behavior of the cmdlet `New-SmbShare`. If you would use this configuration.

```powershell
SmbShare 'Integration_Test'
{
    Name         = 'MyShare'
    Path         = 'c:\Temp'
    FullAccess   = @()
    ChangeAccess = @()
    ReadAccess   = @()
    NoAccess     = @()
}
```

The share would be created with the group 'Everyone' having read access to the share.  This is because the cmdlet `New-SmbShare` does this by design (can't find a way to make it stop). If you add any other user or group as having read access, then 'Everyone' is not added.
This leads to that it is not possible to have this configuration. Because `Test-DscConfiguration` (`Test-TargetResource`) will always fail since 'Everyone' will be reported as having read access and the property ReadAccess will return `@('Everyone')`.

```powershell
SmbShare 'Integration_Test'
{
    Name         = 'MyShare'
    Path         = 'c:\Temp'
    FullAccess   = @()
    ChangeAccess = @('User1')
    ReadAccess   = @()
    NoAccess     = @()
}
```

It would not be possible to remove the 'Everyone' access permission either, because we are only allowed to have this configuration once.

I see some options to solve this.

1. Make `@('Everyone')` the default for parameter `ReadAccess` so user must specify another (dummy) account to remove it.
2. Remove the access permission 'Everyone' (if it exist) as a second step after the share has been created using `New-SmbShare`.
3. Remove the `*Access`-parameters, and move them to a new resource SmbShareAccess which handles the permissions, and uses other cmdlets to add, remove, block and unblock access permissions.

I'm leaning towards option 2.

**Comment by kungfu71186** [comment]
> I have a slight problem with this resource, and it is the default behavior of the cmdlet `New-SmbShare`. If you would use this configuration.
> 
> ```powershell
> SmbShare 'Integration_Test'
> {
>     Name         = 'MyShare'
>     Path         = 'c:\Temp'
>     FullAccess   = @()
>     ChangeAccess = @()
>     ReadAccess   = @()
>     NoAccess     = @()
> }
> ```
> 
> The share would be created with the group 'Everyone' having read access to the share. This is because the cmdlet `New-SmbShare` does this by design (can't find a way to make it stop). If you add any other user or group as having read access, then 'Everyone' is not added.
> This leads to that it is not possible to have this configuration. Because `Test-DscConfiguration` (`Test-TargetResource`) will always fail since 'Everyone' will be reported as having read access and the property ReadAccess will return `@('Everyone')`.
> 
> ```powershell
> SmbShare 'Integration_Test'
> {
>     Name         = 'MyShare'
>     Path         = 'c:\Temp'
>     FullAccess   = @()
>     ChangeAccess = @('User1')
>     ReadAccess   = @()
>     NoAccess     = @()
> }
> ```
> 
> It would not be possible to remove the 'Everyone' access permission either, because we are only allowed to have this configuration once.
> 
> I see some options to solve this.
> 
> 1. Make `@('Everyone')` the default for parameter `ReadAccess` so user must specify another (dummy) account to remove it.
> 2. Remove the access permission 'Everyone' (if it exist) if `ReadAccess` equals `@()`, as a second step after the share has been created using `New-SmbShare`.
> 3. Remove the `*Access`-parameters, and move them to a new resource SmbShareAccess which handles the permissions, and uses other cmdlets to add, remove, block and unblock access permissions.
> 
> I'm leaning towards option 2.

Ok this is weird. The spec does say that default is none. If i pass in None, I get a user account None. The sid is an actual user though and it's not using a built-in sid. This led me into trying S-1-0-0, which does work! I would use that.

```
New-SmbShare -Name "deleteme" -Path "C:\" -ReadAccess 'NULL SID'

Name     ScopeName Path Description
----     --------- ---- -----------
deleteme *         C:\

```

```
Get-SmbShareAccess -Name "deleteme"
Name     ScopeName AccountName AccessControlType AccessRight
----     --------- ----------- ----------------- -----------
deleteme *         NULL SID    Allow             Read
```

**Comment by johlju** [comment]
Actually it seems that if removing the automatically added 'Everyone' from read access, then 'Everyone' is instead moved to NoAccess property so that Everyone in 'Denied'. It seems that by design an access rule must exist. If adding a user to any other access permission, 'Everyone' is not added.

So this is only a problem when specifying all access permission with empty collections, see below.

```
SmbShare 'Integration_Test'
{
    Name         = 'MyShare'
    Path         = 'c:\Temp'
    FullAccess   = @()
    ChangeAccess = @()
    ReadAccess   = @()
    NoAccess     = @()
}
```

@kungfu71186 thanks for finding the `Null SID` (S-1-0-0) idea! In the above scenario, when all collections is empty, we should add `Null SID` to the `NoAccess` parameter. So that there is no way anything get permission. 

```
PS> New-SmbShare -Name "deleteme" -Path "C:\Temp" -NoAccess 'NULL SID'

Name     ScopeName Path    Description
----     --------- ----    -----------
deleteme *         C:\Temp


PS> Get-SmbShareAccess -Name "deleteme"

Name     ScopeName AccountName AccessControlType AccessRight
----     --------- ----------- ----------------- -----------
deleteme *         NULL SID    Deny              Full
```

In this case, maybe we should also remove the `Null SID`

**Comment by johlju** [comment]
if using this configuration, will will ignore and just assume that the user knows the default is that Everyone is added as read access permission. We should note it in the documentation though.

```
SmbShare 'Integration_Test'
{
    Name         = 'MyShare'
    Path         = 'c:\Temp'
}
```

**Comment by johlju** [comment]
After thinking on this during the day, I think we instead just throw an error if all of the access permission parameters are configured with empty collections. The reason is that it is not possible to modify the permissions manually if using an configuration where all the access permission parameters are empty collections, the manually added users are always removed. Instead it should throw an error saying that either remove the access permission parameters completely or add an account or group to one of the access permission parameters.

**Comment by kungfu71186** [comment]
Seems reasonable. Honestly, this is a very special edge case that probably shouldn't be used anyway. Otherwise you can just specify absent and your problems are solved and it's more secure. I think leaving the default to everyone read access if nothing is specified is fine as well. 

But you have options now :)

**Comment by johlju** [comment]
@kungfu71186 That was my thought as well, if there should be no permission then it would be better to just remove the share. 😄 Yes I appreciate the help, because that was led me to this. 🙇

**Comment by johlju** [comment]
@PlagueHO THis is ready for review now. I'm debugging to find where and how it gets two instances of the module during testing.

**Comment by johlju** [comment]
Returning two module folder locations from `Get-Module -ListAvailable`
```
VERBOSE: C:\projects\computermanagementdsc\Modules\ComputerManagementDsc\ComputerManagementDsc.psd1
VERBOSE: C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ComputerManagementDsc\ComputerManagementDsc.psd1
```

First one is imported here:
https://github.com/PowerShell/DscResource.Tests/blob/4c919dcda0fb1e52e645bcbdf9c40b9f9e4a43c6/TestHelper.psm1#L336

Second one is here:
https://github.com/PowerShell/DscResource.Tests/blob/4c919dcda0fb1e52e645bcbdf9c40b9f9e4a43c6/Meta.Tests.ps1#L595-L605

The problem might be that the meta tests are not run first as it is in a "non-harness modul". But why is the problem showing now. 🤔

**Comment by PlagueHO** [comment]
Awesome stuff @johlju - I'll review this weekend! Sorry about not commenting earlier. Day job :/

**Comment by PlagueHO** [comment]
That is really strange. Perhaps it is just better if I do the work to get this off Harness mode? It won't take me long to do - maybe a couple of hours?

**Comment by johlju** [comment]
@PlagueHO Yeah, you were planning on doing it anyway, so lets do that. But no hurry, I won't be available this weekend to fix any review comments, so take your time. 😄 

I just ran the dev version, and it is passing. Maybe it is the unit test template or integration test template that messes this up. 🤔

**Comment by PlagueHO** [comment]
@johlju - I've completed the harness refactor. I'm just waiting to get #195 through and then I'll rebase onto dev again with the refactor and submit the PR for review.

Might need to get you to review it though :cry: It is mostly just file moves and adjustments to the test headers.

**Comment by johlju** [comment]
No problem, I will help review :smile:

**Comment by johlju** [comment]
I will look into getting the missed integration tests into this PR this weekend, and also rebase when the refactor PR is merged.

**Comment by PlagueHO** [comment]
Cool. I've just got back from a work trip in Australia, so I'll get onto this tomorrow when I wake up :grin:

**Comment by PlagueHO** [comment]
@johlju - Should be good to rebase now! Let me know and I'll begin the review.

**Comment by johlju** [comment]
@PlagueHO Tests are passing. Ready for review. It's a big one, so I expect a lot of grammatical comments too. 😄

**Comment by johlju** [comment]
I cleanup up the Get-function a tiny bit, that showed a problem in the mocked code. All good for review again. 😄

**Comment by PlagueHO** [comment]
Hi @johlju ! Looking forward to getting this one through. I'm just focusing on the Global Azure Bootcamp this week (it is on 27th of April), but once that is done I'm all clear to catch up on DSC work. Sorry about the delay.

**Comment by johlju** [comment]
No problem, you mentioned it on Slack, so I figured that was what keeping you away :smile:

No hurry with any of my PRs.

**Comment by johlju** [comment]
I will run the unit tests on a DC so I can run the tests locally and get that code coverage up. Haven't gotten the stubs to work fully yet. :/

**Comment by johlju** [comment]
Deleted the last comment I made as it was not meant for this PR 😄 

@PlagueHO This one is ready for review whenever you have time. No hurry!

**Comment by johlju** [comment]
@PlagueHO I will get on this again. I have forgot about it. :/

**Comment by johlju** [comment]
I have not forgotten this again, I just need to review a lot of PR's and maintain repos so it takes a while until I can get to this. :/ But will get back to this as soon as I have fixed/closed all abandoned in SqlServerDsc.

**Comment by PlagueHO** [comment]
No worries @johlju - I knew you hadn't forgotten it! I know how busy you are! :grin: Hoping to have some time to give you a hand over in ActiveDirectory this weekend when I'm back home.

**Comment by PlagueHO** [comment]
I'll get onto this review shortly @johlju - can you resolve the conflicts?

**Comment by johlju** [comment]
@PlagueHO rebased 😄

**Comment by PlagueHO** [comment]
Time to review! :grin:

**Comment by johlju** [comment]
@PlagueHO Hope that was it! Ready for review again. 😃

**Comment by PlagueHO** [comment]
Awesome @johlju -will get onto it tonight.

**Pull request merged**
