### PR TITLE
ScheduledTask: IdleWaitTimeout fix & BuiltInAccount added

### LINKED ISSUE #130: xScheduledTask: Cannot create task to run as NetworkService
This logic would need changed such that if logontype is 'serviceaccount' and the password is null or empty, don't set the password.

```
        if ($PSBoundParameters.ContainsKey('ExecuteAsCredential'))
        {
            $username = $ExecuteAsCredential.UserName
            $registerArguments.Add('User', $username)

            # If the LogonType is not specified then set it to password
            if ([System.String]::IsNullOrEmpty($LogonType))
            {
                $LogonType = 'Password'
            }

            if ($LogonType -notin ('Interactive', 'S4U'))
            {
                # Only set the password if the LogonType is not interactive or S4U
                $registerArguments.Add('Password', $ExecuteAsCredential.GetNetworkCredential().Password)
            }
        }
        else
        {
            $username = 'NT AUTHORITY\SYSTEM'
            $registerArguments.Add('User', $username)
            $LogonType = 'ServiceAccount'
        }
```

Example resource which should work, but fails with a 'password is null' error due to the logic above.:
```
$network_service_cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList ("NT AUTHORITY\NETWORK SERVICE", (new-object System.Security.SecureString))

xScheduledTask 'sql_backups_daily'
    {
        TaskName            = 'my_task'
        TaskPath            = '\CustomTasks'
        ActionExecutable    = 'C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe'
        ActionArguments     = "-File `"C:\scripts\my_script.ps1`""
        ScheduleType        = 'Daily'
        DaysInterval        = 1
        RepetitionDuration  = 'Indefinitely'
        ExecuteAsCredential = $network_service_cred
        LogonType           = 'ServiceAccount'
        Enable              = $true
    }
```

### LINKED ISSUE #186: ScheduledTask: IdleWaitTimeout returned from Get-TargetResource always null
Background: Working on a fork to implement run as NETWORK SERVICE and I was getting Test-TargetResource invalidly returning false. Traced it to this issue among others. 

The bug is caused by the following line in Get-TargetResource:
`IdleWaitTimeout                 = ConvertTo-TimeSpanStringFromScheduledTaskString -TimeSpan $settings.IdleSettings.IdleWaitTimeout`
The problem is IdleSettings object does not have a IdleWaitTimeout property, but it does have a WaitTimeout property.

I have implemented a fix in my fork, creating this issue to reference in CHANGELOG.md

### PR DESCRIPTION
**Pull request by djwork**
#### Pull Request (PR) description
ScheduledTask:
  Fix to IdleWaitTimeout returned from Get-TargetResource always null
  Added BuiltInAccount property to support running task as a builtin account

#### This Pull Request (PR) fixes the following issues
    - Fixes #186 
    - Fixes #130 

#### Task list
- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [X] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/187)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@djwork - looks like you've got some merge conflicts there - can you rebase against Dev?

**Comment by djwork** [comment]
@PlagueHO did my rebase come through? I am new to pull requests and rebasing

**Comment by djwork** [comment]
Is this still waiting on code fix?

**Comment by djwork** [comment]
@PlagueHO fixed the merge conflicts

**Comment by PlagueHO** [comment]
Hi @djwork - I think the rebase might have gone a bit wrong (I've been there more times than I can count :grin:). Because you've not made a branch in your repo (just developed in dev), what you'd need to do is rebase against the upstream fork dev branch (I'm assuming you've registered a remote fork `upstream` with https://github.com/PowerShell/ComputerManagementDsc).

```bash
git rebase upstream dev
```

It should the replay all your commits onto the upstream dev branch. I generally create a branch of my own dev and then just pull all change from the upstream fork into my dev branch and do a squash rebase before I commit (to get rid of all my commits that say things like "This better work" and "another try" :grin:)

**Comment by djwork** [comment]
I'm going to abandon this pull request and try again with a fresh one

**Pull request closed without merging**
