### PR TITLE
BREAKING CHANGE: Renamed ComputerManagement to ComputerManagementDsc - Fixes #119

### LINKED ISSUE #119: Convert Module Name to ComputerManagementDsc
As per recent DSC Resource Naming guidelines changes:
https://github.com/PowerShell/DscResources/blob/master/Naming.md

This should also include merging of SystemLocaleDsc and TimezoneDsc

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
- BREAKING CHANGE:
  - Renamed ComputerManagement to ComputerManagementDsc - fixes [Issue #119](https://github.com/PowerShell/xComputerManagement/issues/119).
  - Changed all MSFT_xResourceName to MSFT_ResourceName.
  - Updated DSCResources, Examples, Modules and Tests with new naming.
  - Updated Year to 2018 in License and Manifest.
  - Updated README.md from xComputerManagement to ComputerManagementDsc.
- OfflineDomainJoin:
  - Cleaned up spacing in strings file to make consistent with other
    resources.
- VirtualMemory:
  - Converted strings to single quotes in integration test.

**This Pull Request (PR) fixes the following issues:**
- Fixes #119

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - would you mind looking at this one if you get a moment?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xcomputermanagement/151)

### CODE REVIEW

**Comment by johlju** [comment]
Just tiny review comments. :) Couldn't find anything wrong with the rename.

---

Reviewed 117 of 160 files at r1.
Review status: 61 of 62 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[CHANGELOG.md, line 6 at r1](https://beta.reviewable.io/reviews/powershell/xcomputermanagement/151#-L9QOwSg-Z9XPAw8UMZv:-L9QOwSg-Z9XPAw8UMZw:b-ot3v09) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6d4868cd307be32bb517d6edca1189c635e24005/CHANGELOG.md#L6)):*
> ```Markdown
> 
> - BREAKING CHANGE:
>   - Renamed ComputerManagement to ComputerManagementDsc - fixes [Issue #119](https://github.com/PowerShell/xComputerManagement/issues/119).
> ```

URL should change

---

*[CHANGELOG.md, line 7 at r1](https://beta.reviewable.io/reviews/powershell/xcomputermanagement/151#-L9QP1Da1pzU3_Emo12W:-L9QP1Db1-RTjRERrDdE:brrn0xp) ([raw file](https://github.com/powershell/xcomputermanagement/blob/6d4868cd307be32bb517d6edca1189c635e24005/CHANGELOG.md#L7)):*
> ```
> MSFT_xResourceName to MSFT_R
> ```

We should escape underscore 'MSFT\_xResourceName to MSFT\_ResourceName' in these situations.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xcomputermanagement/151#-:-L9QRUnG3mGlLaFXUP7G:b-a6qipp)*

**Comment by PlagueHO** [comment]
Doh! Missed this one @Johlju - should be all good to go now.

---

Review status: 60 of 62 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 6 at r1](https://reviewable.io/reviews/powershell/computermanagementdsc/151#-L9QOwSg-Z9XPAw8UMZv:-LB-nRCHEVnYoFJN2g4s:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/6d4868cd307be32bb517d6edca1189c635e24005/CHANGELOG.md#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

URL should change
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 7 at r1](https://reviewable.io/reviews/powershell/computermanagementdsc/151#-L9QP1Da1pzU3_Emo12W:-LB-nn7NCagowNkW0Meo:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/6d4868cd307be32bb517d6edca1189c635e24005/CHANGELOG.md#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> MSFT_xResourceName to MSFT_R
> ```

We should escape underscore 'MSFT\_xResourceName to MSFT\_ResourceName' in these situations.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/151#-:-LB-no9B3lyjmL01h_kI:b-qm77vy)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/151#-:-LB1IQor2pv04N9V2NJG:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thanks @johlju - I've also renamed this module in the DSCResouces repo in the exising PR I've got open.

**Pull request merged**
