### PR TITLE
Computer: AD join with server

### LINKED ISSUE #161: Computer: add parameter to define the domain controller when joining
**Details of the scenario you tried and the problem that is occurring:**
It is not possible to define the domain controller a computer will use to join.
In some specific scenario (implying network filtering), it is mandatory to define the server.
The PowerShell cmdlet `Add-Computer` has a `server` parameter that can be leveraged.

**The DSC configuration that is using the resource (as detailed as possible):**
Computer

**Version of the Operating System and PowerShell the DSC Target Node is running:**
All Windows

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
5.0.0

### PR DESCRIPTION
**Pull request by r3dlin3**
**Pull Request (PR) description**
Add a new parameter "server" to define the domain controller to join the server to.

**This Pull Request (PR) fixes the following issues:**
Fixes #161

**Task list:**
- [X] Change details added to Unreleased section of CHANGELOG.md?
- [X] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [X] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/162)

### CODE REVIEW

**Comment by johlju** [comment]
@r3dlin3 Great work on this one! I tagged @PlagueHO to review this one.

@PlagueHO I requested review from you, but let me know if you are to busy, I will help then.

**Comment by PlagueHO** [comment]
Great stuff @r3dlin3 ! Thank you! Just a few minor style things. Is it possible to add some unit test coverage for the `Get-LogonServer` cmdlet and also is it possible to add a new unit test case for `Set-TargetResource` to cover the new functionallity?

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 12 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG6dR5-i1HplSB4u_a:-LDG6dR5-i1HplSB4u_b:b8cbumj) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/CHANGELOG.md#L12)):*
> ```Markdown
>   It was not exported in ComputerManagementDsc.ResourceHelper and not
>   used.
> - Add `server` parameter to `Computer` resource
> ```

Could you add a ` - fixes [Issue #161](https://github.com/PowerShell/ComputerManagementDsc/issues/161).` to the end of this line?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 50 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG76xTA3NEKIGTmzb8:-LDG76xTA3NEKIGTmzb9:b-985zqu) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L50)):*
> ```PowerShell
> 
>     .PARAMETER Server
>         The server to use to join the domain.
> ```

Could you maybe say "The Active Directory Domain Controller to use to join the domain" to make it clear that this is the name of the DC?

And throughout.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 226 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9c6p4Fxpszf0Ap3w:-LDG9c6p4Fxpszf0Ap3x:btkxc3a) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L226)):*
> ```PowerShell
>             else
>             {
>                 $splat = @{
> ```

Could you change the variable name to $addComputerParameters rather than the generic $splat?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 227 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9V874t1eM5UC1TNx:-LDG9V874t1eM5UC1TNy:b-acs41j) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L227)):*
> ```PowerShell
>             {
>                 $splat = @{
>                     DomainName=$DomainName
> ```

Could you add spaces around the = ?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 231 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9ZvnDyT0HHv-5yVl:-LDG9ZvnDyT0HHv-5yVm:b-acs41j) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L231)):*
> ```PowerShell
>                     Force=$true
>                 }
>                 $rename=$false
> ```

Could you add spaces around the = ?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 235 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDGA5JIEChMqeqNau_W:-LDGA5JIEChMqeqNau_X:b-acs41j) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L235)):*
> ```PowerShell
>                 {
>                     $splat.Add("NewName", $Name)
>                     $rename=$true
> ```

Could you add spaces around the = ?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 236 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9kgA7sms18v-3KiP:-LDG9kgA7sms18v-3KiQ:b-7y38we) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L236)):*
> ```PowerShell
>                     $splat.Add("NewName", $Name)
>                     $rename=$true
>                 }
> ```

Could you add a blank line here?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 241 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9npb9BGFQZguzjU8:-LDG9npb9BGFQZguzjU9:b-ywbvkn) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L241)):*
> ```PowerShell
>                     $splat.Add("UnjoinDomainCredential", $UnjoinCredential)
>                 }
>                 if ($JoinOU)
> ```

Could you add a blank line above this line?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 245 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9qbo3R1h2KBM8cxl:-LDG9qbo3R1h2KBM8cxm:b-ywbvkn) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L245)):*
> ```PowerShell
>                     $splat.Add("OUPath", $JoinOU)
>                 }
>                 if ($Server)
> ```

Could you add a blank line above this line?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 252 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9vW1CprzogxT-bcF:-LDG9vW1CprzogxT-bcG:b-ywbvkn) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L252)):*
> ```PowerShell
>                 # Rename the computer, and join it to the domain.
>                 Add-Computer @splat
>                 if ($rename)
> ```

Could you add a blank line above this line?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 613 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG7bti3y3-TmmnsPj8:-LDG7bti3y3-TmmnsPj9:b-5jsn0r) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L613)):*
> ```PowerShell
>     .SYNOPSIS
>         Returns the logon server.
> ```

Could you remove the blank line here?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 621 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG7nkg4NgqobuU0NwG:-LDG7nkg4NgqobuU0NwH:b-890cz2) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L621)):*
> ```PowerShell
>     param
>     (
>         [Parameter()]
> ```

This parameter doesn't look like it is used - can it be removed?

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.schema.mof, line 11 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG8ReI0V8gqMMuwYt8:-LDG8ReI0V8gqMMuwYt9:b-m2ddqm) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.schema.mof#L11)):*
> ```
>     [Write, Description("The name of the workgroup.")] String WorkGroupName;
>     [Write, Description("The value assigned here will be set as the local computer description.")] String Description;
>     [Write, Description("The server used to join a domain")] String Server;
> ```

Could you maybe say "The Active Directory Domain Controller to use to join the domain" to make it clear that this is the name of the DC?

---

*[Modules/ComputerManagementDsc/Examples/Resources/Computer/2b-JoinDomain.ps1, line 1 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG8WS-22t_AZmWXo0o:-LDG8WS-22t_AZmWXo0p:b-oux0rj) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/Examples/Resources/Computer/2b-JoinDomain.ps1#L1)):*
> ```PowerShell
> <#
> ```

Could you change the name of the file to be 7-JoinDomainSpecifyingDC.ps1? I'm not sure that the auto-documentation code supports the 2b.

---

*[Modules/ComputerManagementDsc/Examples/Resources/Computer/2b-JoinDomain.ps1, line 4 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG8yC500fQmvVlQlnJ:-LDG8yC500fQmvVlQlnK:bsjkalm) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/Examples/Resources/Computer/2b-JoinDomain.ps1#L4)):*
> ```PowerShell
>     .EXAMPLE
>     This configuration sets the machine name to 'Server01' and
>     joins the 'Contoso' domain.
> ```

Could you specify that this example joins the domain sing a specified DC 'dc1.contoso.com'

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-:-LDGAHhk8lRXKMy3xjGf:b-8xzskt)*

**Comment by johlju** [comment]
@r3dlin3 Thanks for resolving the review comments! 

When you have resolved the review comments, or if you need to discuss a comment. Could you please go into Reviewable and write 'Done' (or click the done-button) on each of the review comments. This allows us to acknowledge (resolve) the review comments and we know that you are done with each change. After you written 'Done' on each review comment,  or comment on the review comment if it needs further discussion, then click the big green 'Publish' button on top of the page. That will send all your comments back as one big comment to this PR.
You find Reviewable if you click on the big purple Reviewable-button in the PR description.

**Comment by r3dlin3** [comment]
Review status: 0 of 5 files reviewed, 15 unresolved discussions (waiting on @PlagueHO)

---

*[CHANGELOG.md, line 12 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG6dR5-i1HplSB4u_a:-LFTUHMO9XgE8kKqAE18:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/CHANGELOG.md#L12)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add a ` - fixes [Issue #161](https://github.com/PowerShell/ComputerManagementDsc/issues/161).` to the end of this line?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 50 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG76xTA3NEKIGTmzb8:-LFTULfO0by8gkM22J6c:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L50)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you maybe say "The Active Directory Domain Controller to use to join the domain" to make it clear that this is the name of the DC?

And throughout.
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 226 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9c6p4Fxpszf0Ap3w:-LFTUQL320jvDW9sdywx:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L226)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you change the variable name to $addComputerParameters rather than the generic $splat?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 227 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9V874t1eM5UC1TNx:-LFTUR0-2sCf8IlxdG-L:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L227)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add spaces around the = ?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 231 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9ZvnDyT0HHv-5yVl:-LFTUSg_9365lLIs2SiT:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L231)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add spaces around the = ?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 235 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDGA5JIEChMqeqNau_W:-LFTUTHI4V-1Z5fkrneh:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L235)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add spaces around the = ?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 236 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9kgA7sms18v-3KiP:-LFTUTYt3lFuwrNuox7S:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L236)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add a blank line here?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 241 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9npb9BGFQZguzjU8:-LFTUUIrEq5YTztKSsK2:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L241)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add a blank line above this line?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 245 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9qbo3R1h2KBM8cxl:-LFTUVCV1QsFO-2r2kgm:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L245)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add a blank line above this line?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 252 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG9vW1CprzogxT-bcF:-LFTUYy-8Ml4RpOxBPXt:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L252)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you add a blank line above this line?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 613 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG7bti3y3-TmmnsPj8:-LFTU_T7Cr6S6mtdy7WC:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L613)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you remove the blank line here?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1, line 621 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG7nkg4NgqobuU0NwG:-LFTUbCd9moI8OV8zsGN:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.psm1#L621)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This parameter doesn't look like it is used - can it be removed?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.schema.mof, line 11 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG8ReI0V8gqMMuwYt8:-LFTUc5n4ud2TmT1niKx:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/DSCResources/MSFT_Computer/MSFT_Computer.schema.mof#L11)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you maybe say "The Active Directory Domain Controller to use to join the domain" to make it clear that this is the name of the DC?
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/Examples/Resources/Computer/2b-JoinDomain.ps1, line 1 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG8WS-22t_AZmWXo0o:-LFTUdJcB9Xs06TAPX8_:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/Examples/Resources/Computer/2b-JoinDomain.ps1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you change the name of the file to be 7-JoinDomainSpecifyingDC.ps1? I'm not sure that the auto-documentation code supports the 2b.
</blockquote></details>

Done.

---

*[Modules/ComputerManagementDsc/Examples/Resources/Computer/2b-JoinDomain.ps1, line 4 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/162#-LDG8yC500fQmvVlQlnJ:-LFTUdsf2FUN8JP0jn3I:b-896fix) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1c39dc8b3c7c8c753b33bf05eeb2a0842dc9bde9/Modules/ComputerManagementDsc/Examples/Resources/Computer/2b-JoinDomain.ps1#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you specify that this example joins the domain sing a specified DC 'dc1.contoso.com'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/162)*

**Comment by r3dlin3** [comment]
is there anything else I should do?

**Comment by r3dlin3** [comment]
No problem.
Thanks for your answer.

**Comment by PlagueHO** [comment]
I'll get this one done tomorrow night after work! Sorry about the delay there @r3dlin3 - I'd do it tonight but I've run out of time (catching up on other fixes).

**Pull request merged**
