### PR TITLE
Add SystemLocale Resource - Fixes #50

### LINKED ISSUE #50: Move SystemLocale resource from SystemLocaleDSC to xComputerManagement
The SystemLocale resource currently resides inside of it's own module (SystemLocaleDSC).
I believe it makes more sense inside of xComputerManagement\xComputer resource as an optional parameter.

Let me know what you guys think. I've already submitted a PR ([#49](https://github.com/PowerShell/xComputerManagement/pull/49))

Liam

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR migrates SystemLocale from SystemLocaleDsc.

#### This Pull Request (PR) fixes the following issues

- Fixes #50

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing this one?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/280)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @johlju - if you're looking for something to do, you could review this one for me? :grin:

**Comment by johlju** [comment]
Haha will do! 😄

**Comment by PlagueHO** [comment]
@johlju - actually, hold off for a moment- I think something has happened with the rebase :cry:

**Comment by PlagueHO** [comment]
I think I'll recreate this PR because during the change I renamed a localization folder to correct the case, and it has made the rebase "problematic". I think I'll just recreate this branch and PR to be safe.

**Comment by johlju** [comment]
Okay! Tag me and I will start the review on the new PR :)

**Pull request closed without merging**
