### PR TITLE
BREAKING CHANGE: PowerPlan: Add IsActive read-only property

### LINKED ISSUE #171: PowerPlan: Add a read-only property IsActive
**Details of the scenario you tried and the problem that is occurring:**
Suggest we add a read-only property `IsActive` to the resource PowerPlan, and set that to `$plan.isActive` instead of setting the `$Name` to `$null` in `Get-TargetResource` if the plan is not the active plan.

https://github.com/PowerShell/ComputerManagementDsc/blob/c0a60754c2ec537f1668e4a3cf6ca7423a8c9a2c/Modules/ComputerManagementDsc/DSCResources/MSFT_PowerPlan/MSFT_PowerPlan.psm1#L67-L76

**The DSC configuration that is using the resource (as detailed as possible):**
Any configuration that hasn't the power plan as the active power plan.

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by TraGicCode**
#### Pull Request (PR) description

Added Read-Only property call IsActive.

#### This Pull Request (PR) fixes the following issues

Fixes #171 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/193)

### CODE REVIEW

**Comment by TraGicCode** [comment]
Hey @johlju ,

Are you able to review this.  I believe i did everything correct in regards to implementing a read-only property.

Thanks!

**Comment by TraGicCode** [comment]
Hey @plagueho,

I want to remove the verbose messaging in the get target resource that says whether or not the power plan is active or not since it’s a bit redundant since now get target resource returns that information.  Do you have any issues with this?

**Comment by TraGicCode** [comment]
I’m not at a computer now but I forgot this might still be helpful if the test and set methods are calling this function and you want to know what’s happening during a dsc run.

**Comment by TraGicCode** [comment]
___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/powershell/computermanagementdsc/193#-LNxVcP7Ew_YkGtBjx5Y:-LNzRJX1Bk8-TuYErosX:b-6r8o1g) ([raw file](https://github.com/powershell/computermanagementdsc/blob/1f7ca086210cf0c4951bedc0286ea920be6f0c14/CHANGELOG.md#L11)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change . to - for consistency and in a full stop?
</blockquote></details>

I think this is Done.  You might need to point to a line as an example if i didn't get this correct.

**Comment by johlju** [comment]
> I want to remove the verbose messaging in the get target resource that says whether or not the power plan is active or not since it’s a bit redundant since now get target resource returns that information. Do you have any issues with this?

Two reason to keep it. First, there is a PSSA rule that will fail if there is no Write-Verbose in the Get-function. Also, the verbose message is for debug purpose when running the configuration with verbose messages, to show what the resource are returning, or running the Get-DscConfiguration where only the Get-function is called. 
So I suggest we keep the verbose messages.

**Comment by johlju** [comment]
@PlagueHO @TraGicCode as per my review comment, should we consider this as a breaking change? I'm leaning towards not.

**Comment by TraGicCode** [comment]
> @PlagueHO @TraGicCode as per my review comment, should we consider this as a breaking change? I'm leaning towards not.

I'm leaning towards it being a breaking change based on the comment you made shown below



> This does no longer return $null if the plan is not active. I think we should mention that change in the CHANGELOG.md? If users have logic is depending on this returning $null, that logic will fail. So would be good to mentioned that?

While the contract has not changed the behavior has which people might be expecting this to not change.

**Comment by TraGicCode** [comment]
Thanks @johlju as always!

**Comment by PlagueHO** [comment]
Doh! With all this talk about BREAKING CHANGE we actually forgot to mark this as BREAKING CHANGE in the changelog. I'll quickly submit a PR.

**Comment by johlju** [comment]
@PlagueHO Yeah, we totally missed that 😃 Approved the other PR, it's ready for merge.

**Comment by PlagueHO** [comment]
Thanks @johlju - Yeah, I've been a bit distracted with work stuff the last couple of weeks so trying to just keep up with as many PR's as possible in what ever spare time I have. But just not getting much done right now :cry: Might have some spare time this weekend though.

**Comment by TraGicCode** [comment]
Thanks @PlagueHO and @johlju ,

As always great job on your modules and keeping things rolling.

**Comment by johlju** [comment]
@PlagueHO I haven’t much time now either. Gonna try to get something done this weekend too. 

@TraGicCode thank you! Also thank you for your contributions.

**Pull request merged**
