### PR TITLE
ComputerManagementDsc: Add Windows Capability

### LINKED ISSUE #241: WindowsCapability and WindowsCapabilitySet: New Resource(s) Proposal
### Description
A DSC Module around the WindowsCapability cmdlets to manage the enabled and disabled capabilities.  It should work similarly to the WindowsOptionalFeature and WindowsOptionalFeatureSet DSC Resources

### Proposed properties
Name (Key)
LogLevel
LogPath
NoWindowsUpdateCheck (mapped to the `LimitAccess` parameter)
DependsOn
Ensure

### Special considerations or limitations
Originally filed by @mgreenegit in PowerShell/PSDscResources#168.  The discussion in that issue was to include it into ComputerManagementDsc

When executing `Get-WindowsCapability`, the convention for the name is that it ends with three tildes followed by the version number.  It would be great if the DSC Resource only required the name, and not the tildes and version number (or, at the very least, make the tildes and everything to the right of them optional)

### PR DESCRIPTION
**Pull request by Outek**
#### Pull Request (PR) description
Add a new resource to configure Windows Capabilities with Dsc 

#### This Pull Request (PR) fixes the following issues
    - Fixes #241 

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/263)

### CODE REVIEW

**Comment by Outek** [comment]
@PlagueHO It is not finished be far, but maybe you have already some suggestions?

**Comment by Outek** [comment]
Do we need a parameter for a „-Source“. Do we want to be able to modify Images or somerhong like this?

**Comment by PlagueHO** [comment]
Great stuff @Outek - will begin review tonight. I dont think we need Source parameter, at least not initially. We can always add it later if there is a use case.

**Comment by Outek** [comment]
@PlagueHO Any idea, how to fix this errors?

```powershell

he term 'Get-WindowsCapability' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Get-WindowsCapability:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost
 
PowerShell Desired State Configuration does not support execution of commands in an interactive mode. Please ensure that the underlying command is not prompting for user input, such as missing mandatory parameter, confirmation 
prompt etc.
    + CategoryInfo          : OperationStopped: (:) [], CimException
    + FullyQualifiedErrorId : System.NotSupportedException
    + PSComputerName        : localhost

```

**Comment by Outek** [comment]
@PlagueHO Please help me, i have no clue how to get this tests working. For me it's way to complex to understand whats going on or what is not working. and why

**Comment by PlagueHO** [comment]
Hi @Outek , no problem, I'll give you a hand this weekend. Been totally snowed under at work this week.

**Comment by PlagueHO** [comment]
@Outek - nearly there - need to also create stubs for `Add-WindowsCapability` and `Remove-WindowsCapability`.

**Comment by Outek** [comment]
I think there is a Bug in the Set-TargetResource, sorry for this.

**Pull request merged**
