### PR TITLE
ScheduledTask: Added BuiltInUser (Issue #130) & Fixed IdleWaitTimeout…

### LINKED ISSUE #130: xScheduledTask: Cannot create task to run as NetworkService
This logic would need changed such that if logontype is 'serviceaccount' and the password is null or empty, don't set the password.

```
        if ($PSBoundParameters.ContainsKey('ExecuteAsCredential'))
        {
            $username = $ExecuteAsCredential.UserName
            $registerArguments.Add('User', $username)

            # If the LogonType is not specified then set it to password
            if ([System.String]::IsNullOrEmpty($LogonType))
            {
                $LogonType = 'Password'
            }

            if ($LogonType -notin ('Interactive', 'S4U'))
            {
                # Only set the password if the LogonType is not interactive or S4U
                $registerArguments.Add('Password', $ExecuteAsCredential.GetNetworkCredential().Password)
            }
        }
        else
        {
            $username = 'NT AUTHORITY\SYSTEM'
            $registerArguments.Add('User', $username)
            $LogonType = 'ServiceAccount'
        }
```

Example resource which should work, but fails with a 'password is null' error due to the logic above.:
```
$network_service_cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList ("NT AUTHORITY\NETWORK SERVICE", (new-object System.Security.SecureString))

xScheduledTask 'sql_backups_daily'
    {
        TaskName            = 'my_task'
        TaskPath            = '\CustomTasks'
        ActionExecutable    = 'C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe'
        ActionArguments     = "-File `"C:\scripts\my_script.ps1`""
        ScheduleType        = 'Daily'
        DaysInterval        = 1
        RepetitionDuration  = 'Indefinitely'
        ExecuteAsCredential = $network_service_cred
        LogonType           = 'ServiceAccount'
        Enable              = $true
    }
```

### LINKED ISSUE #186: ScheduledTask: IdleWaitTimeout returned from Get-TargetResource always null
Background: Working on a fork to implement run as NETWORK SERVICE and I was getting Test-TargetResource invalidly returning false. Traced it to this issue among others. 

The bug is caused by the following line in Get-TargetResource:
`IdleWaitTimeout                 = ConvertTo-TimeSpanStringFromScheduledTaskString -TimeSpan $settings.IdleSettings.IdleWaitTimeout`
The problem is IdleSettings object does not have a IdleWaitTimeout property, but it does have a WaitTimeout property.

I have implemented a fix in my fork, creating this issue to reference in CHANGELOG.md

### PR DESCRIPTION
**Pull request by djwork**
#### Pull Request (PR) description
ScheduledTask:
  Fix to IdleWaitTimeout returned from Get-TargetResource always null
  Added BuiltInAccount property to support running task as a builtin account

#### This Pull Request (PR) fixes the following issues
    - Fixes #186 
    - Fixes #130 

#### Task list

- [X] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [X] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [X] Comment-based help added/updated.
- [X] Localization strings added/updated in all localization files as appropriate.
- [X] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [X] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/195)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Seems to be working now @djwork - I'll review today.

**Comment by djwork** [comment]
___
*[CHANGELOG.md, line 35 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/195#-LbCOQmf7l-bsMCbFIKc:-LbKh5vwB6UOJ_TUS9OQ:biu6n66) ([raw file](https://github.com/powershell/computermanagementdsc/blob/ec8064a8aa126f5316cb040687a18a3894bf2d82/CHANGELOG.md#L35)):*
> ```
> IdleWaitTimeout
> ```
Line 549 of MSFT_ScheduledTask.psm1
Orig: IdleWaitTimeout                 = ConvertTo-TimeSpanStringFromScheduledTaskString -TimeSpan $settings.IdleSettings.IdleWaitTimeout
Current: IdleWaitTimeout                 = ConvertTo-TimeSpanStringFromScheduledTaskString -TimeSpan $settings.IdleSettings.WaitTimeout

**Comment by djwork** [comment]
___
*[CHANGELOG.md, line 35 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/195#-LbCHmuN22QACdVzBdpA:-LbKhZxT7LFbDm2cvAy7:biluhhg) ([raw file](https://github.com/powershell/computermanagementdsc/blob/ec8064a8aa126f5316cb040687a18a3894bf2d82/CHANGELOG.md#L35)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you move this up to the # Unreleased section?
</blockquote></details>

You have already merged the change in to the dev branch, is it correct to move to unreleased?

**Comment by djwork** [comment]
___
*[Modules/ComputerManagementDsc/DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1, line 1928 at r2](https://reviewable.io/reviews/powershell/computermanagementdsc/195#-LbCNsY49v1x6QH9SdXA:-LbKn13Z4SrA854nvZfH:bnoqjcq) ([raw file](https://github.com/powershell/computermanagementdsc/blob/ec8064a8aa126f5316cb040687a18a3894bf2d82/Modules/ComputerManagementDsc/DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1#L1928)):*
> ```
> $desiredValues.TaskPath = $TaskPath
> ```
Can we cross that bridge when we get to it? Otherwise the different way to solve is a smarter Test-DscParameterState function but that is a much more invasive change

**Comment by djwork** [comment]
___
*[CHANGELOG.md, line 42 at r5](https://reviewable.io/reviews/powershell/computermanagementdsc/195#-LbXEGgC0lTGmX4ptxWc:-Lb_7lrE0ARWIbmoco6_:b-d6j9he) ([raw file](https://github.com/powershell/computermanagementdsc/blob/5e6a3020d41446e3da6eecf6f67f8e0973f96daa/CHANGELOG.md#L42)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this is still in the wrong place - needs to be moved up to # Unreleased.

Once that is sorted I reckon we are ready to go.
</blockquote></details>

rebased my fork from dev does that fix the problem?

**Pull request merged**
