### PR TITLE
RemoteDesktopAdmin: New Resource to configure Remote Desktop for Administration

### LINKED ISSUE #224: RemoteDesktopAdmin: New resource proposal
### Description

There is currently a separate DSC module [xRemoteDesktopAdmin](https://github.com/PowerShell/xRemoteDesktopAdmin) which contains a single resource for configuring 'Remote Desktop for Administration' on a Windows server, along with the RDP Authentication security. The resource code for this hasn't been touched for 4 years and has outstanding bugs, and also needs making `SingleInstance`. I started to submit PRs to bring the module up to HQRM standards and fix the bugs, but then though that perhaps rather than having a separate module for one simple resource, it would be better integrated into the `ComputerManagementDsc` module.
I've already re-written the resource to HQRM standards along with Pester tests.

### Proposed properties

```
[ClassVersion("1.0.0.0"), FriendlyName("RemoteDesktopAdmin")]
class MSFT_RemoteDesktopAdmin : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required, Description("Determines whether or not the computer should accept remote desktop connections.  Present sets the value to Enabled and Absent sets the value to Disabled."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("User Authentication.  Setting this value to Secure configures the machine to require Network Level Authentication (NLA)."), ValueMap{"Secure","NonSecure"}, Values{"Secure","NonSecure"}] String UserAuthentication;
};
```

### Special considerations or limitations

None

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR adds a new resource `RemoteDesktopAdmin` to configure Remote Desktop for Administration. This resource replaces the separate `xRemoteDesktopAdmin` module.

#### This Pull Request (PR) fixes the following issues

- Fixes #224 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/227)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Can you resolve conflicts on this one @X-Guardian ? I'll try and get started on the review.

**Comment by PlagueHO** [comment]
@X-Guardian - I might wait to review and merge this one after this one is through: https://github.com/PowerShell/ComputerManagementDsc/pull/216 - Hopefully @johlju will be get the changes made to it soon and I can work on this one.

This is because it will require changes to this PR.

**Comment by johlju** [comment]
@X-Guardian Will this completely replace (deprecate) xRemoteDesktopAdmin? If so I will change the status in this issue https://github.com/PowerShell/DscResources/issues/374 to in progress. :)

**Comment by X-Guardian** [comment]
Yes it will.

**Comment by X-Guardian** [comment]
I've done the localization on the resource, so hopefully no changes will be required after #216 is merged. I hope I don't regret saying this!

**Comment by PlagueHO** [comment]
Can you rebase this one @X-Guardian and I'll get onto the review. Might need to make some changes as well to bring it into alignment with the changes we just merged from @johlju

**Comment by X-Guardian** [comment]
> > _[Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/227)_ status: all files reviewed, 23 unresolved discussions (waiting on @X-Guardian)
> 
> _[DSCResources/MSFT_RemoteDesktopAdmin/MSFT_RemoteDesktopAdmin.psm1, line 53 at r6](https://reviewable.io/reviews/powershell/computermanagementdsc/227#-Lj3JI5R0gjAFNfLB1D0:-LjDRCl09JBVpL_m50-g:bdbd2zi) ([raw file](https://github.com/powershell/computermanagementdsc/blob/90e7016eb5c267af558338292ce4dcd200b23b6d/DSCResources/MSFT_RemoteDesktopAdmin/MSFT_RemoteDesktopAdmin.psm1#L53)):_
> 
> Previously, johlju (Johan Ljunggren) wrote…
> I do agree that there are conditions that don't get handled with this pattern (or using an enum), but in this case we're not handling them in the switch either 😁 The question would be for me is: what is the best way to handle the edge cases ($null, no match) with each pattern - and which is more readable. I think the switch can be more readable for 2-3 cases, but if there are any more than 3 then it quickly becomes excessive code to express a simple mapping. Instead and if...else handling the specific edge cases might result in smaller/simpler code.
> 
> This discussion actually highlights something: the unit tests should describe the expected behavior for these edge cases, but I don't think the scenarios of $null, no match etc are specifically covered in the unit tests. It would be a good idea to put tests in for these edge cases and then we can always refactor to improve readability (or not) later on.

I've done some testing on the `fDenyTSConnections` registry setting, and the Remote Desktop service actually treats it as a boolean, i.e. zero is not denied (false) any other value is denied (true). I'll therefore use the same logic and re-code this as an if/else block.
My conjecture is that `UserAuthentication` is the same, but at the moment with Server 2019, I'm not able to make a non-NLA connection no matter what value I have in the setting! I'll continue testing maybe going back to 2012 R2.

**Comment by PlagueHO** [comment]
Sorry about the delay on this one @X-Guardian - I'll get back onto this one tomorrow night (missed your updates - sorry about that).

**Comment by PlagueHO** [comment]
Hi @X-Guardian - are you able to rebase this one onto Dev branch and correct the CHANGELOG.MD issues?

**Pull request merged**
