### PR TITLE
PowerPlan: Windows APIs instead of WMI (alternative for PR #202)

### LINKED ISSUE #59: MSFT_xPowerPlan should use power plan guid
On non-english Windows, power plans names are localized.  Using power plan's GUID instead would make it work as they all seem to be the same across all Windows platforms for standard plans.

### LINKED ISSUE #65: MSFT_xPowerPlan Support for Nano server
MSFT_xPowerPlan support for Nano server is currently missing.
There is already a module available that does this and it could easily be merged 
https://github.com/J0F3/cPowerPlan

If nobody else is working on it i will properly take a look at how it could be done.

### LINKED ISSUE #155: xPowerPlan: Trying to use it on Windows 10 fails with no Activate method error
Please, observe the following code:
```
$Name = "High Performance"
$getCimInstanceArguments = @{
    Name   = 'root\cimv2\power'
    Class  = 'Win32_PowerPlan'
    Filter = "ElementName = '$Name'"
}
$plan = Get-CimInstance @getCimInstanceArguments
$plan | Invoke-CimMethod -MethodName Activate
```
It works on Windows Server 2012, but fails with no Activate method when ran on Windows 10. Amazingly it works on Windows 8.

Hence the xPowerPlan resource cannot be used on Windows 10.

### PR DESCRIPTION
**Pull request by J0F3**
#### Pull Request (PR) description
This is basically an other variant of the changes in PR #202. This one uses however Windows Native APIs instead of powercfg.exe as a replacement of the WMI classes.
Created this one to have both variants available here with the idea to choose eventually the one to go forward with...

#### This Pull Request (PR) fixes the following issues
- Fixes #59 
- Fixes #155 
- Fixes #65 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ N/A] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [N/A] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/203)

### CODE REVIEW

**Comment by J0F3** [comment]
The resource basically works with calling the Windows APIs but it is probably still some work/refactoring to do here. For example I am basically a little stuck while creating unit tests for the new Get-PowerPlan, Get-PowerPlanFriendlyName, Get-ActivePowerPlan and Set-ActivePowerPlan because of the nature that they call all the P/Invoke classes and static methods...

**Comment by PlagueHO** [comment]
I love this @J0F3 solution! +++ great. I saw your e-mails in the MVP PGI groups about this and watched with great interest and was glad to see that it was identified as a bug. But I like your solution even better. I'll review this weekend (getting a bit late tonight).

**Comment by PlagueHO** [comment]
Hi @J0F3 - I'll try and get to this one as soon as I can. But be aware, I'm going to start work on refactoring this module to move away from the test harness and enable example publishing to PS Gallery. So this will change the layout of the folders in the module significantly and might have cause conflicts with any open PRs.

**Comment by PlagueHO** [comment]
Hi @J0F3 - any chance you could resolve the conflicts on this one and I'll try and get the review done this weekend?

**Comment by J0F3** [comment]
@PlagueHO just resolved the conflicts. Was an easy one because there was only one conflict in the CHANGELOG.md... 😊
I thought also about some refactoring and to capsuling the calls of the native API in to separate functions. So it would be probably a little better testable. But for that I had not the time yet...

**Comment by PlagueHO** [comment]
Cool. Thanks @J0F3 - I'll get onto this tonight/tomorrow. Just a super busy week with day-job this week :cry:

**Comment by J0F3** [comment]
@PlagueHO now worries and hurry. I know how it is... 🙂

**Comment by J0F3** [comment]
No worries. See you probably in Redmond then...? 😉

**Comment by craigeaw** [comment]
Any updates on this?  Would be great to have this available so we don't have to use a Script resource.  Looking forward to it!

**Comment by PlagueHO** [comment]
Thanks for querying this @craigeaw . @J0F3 and I have been away but hopefully this one will get completed soon.

**Pull request merged**
