### PR TITLE
ScheduledTask: Better compatibility with Group LogonType using built-in groups

### PR DESCRIPTION
**Pull request by ShawnHardwick**
#### Pull Request (PR) description
Allows the resource to create Scheduled Task that can run as with 'BUILTIN\Users' and other built in groups. Since groups do not have passwords and ExecuteAsCredential is a PSCredential that requires a non-null password, we extract the username from PSCredential, but ignore the password.

#### This Pull Request (PR) fixes the following issues
None

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/computermanagementdsc/232)

### CODE REVIEW

**Comment by ShawnHardwick** [comment]
Thanks for the suggestions @PlagueHO. This is my first PR so your comments are extremely helpful. It's also interesting to see Appveyor and Reviewable in the pipeline so I'll have to get familiar with this so future PRs can be less error-prone.

**Comment by ShawnHardwick** [comment]
Not exactly sure why the integration test is failing. I've fixed from your suggestions so far though.

**Comment by PlagueHO** [comment]
Hi @ShawnHardwick - I'll take a look tomorrow and advise (getting late here now).

**Comment by ShawnHardwick** [comment]
Hey @PlagueHO, do you have an advice for my failed AppVeyor build?

**Comment by PlagueHO** [comment]
Hi @ShawnHardwick - sorry about the delay! I've got this planned for tonight.

**Comment by ShawnHardwick** [comment]
Looks good now. Thanks for the advice @PlagueHO

**Comment by PlagueHO** [comment]
Hi @ShawnHardwick - sorry about the delay on this one (been a bit behind on this repo). Could you rebase and fix the conflicts and I'll get this one merged ASAP!

**Comment by PlagueHO** [comment]
Hi @ShawnHardwick - let me know when you're ready for me to review again. Thank you!

**Comment by ShawnHardwick** [comment]
@PlagueHO , should be good now.

**Comment by ShawnHardwick** [comment]
@PlagueHO, thanks for the help. This is my first experience with unit tests so it is pretty overwhelming. I updated the Get-CurrentResource function to handle the IDs for group types so that it would pass the test correctly.

**Comment by ShawnHardwick** [comment]
@PlagueHO, that is an older build. Look at the newer one, https://ci.appveyor.com/project/PowerShell/computermanagementdsc/builds/27245454

**Pull request merged**
